// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1utvb0etSX6cPIdFZyCf9XDHICy2Uw8',
    appId: '1:405198768063:android:5f01bd0d85f0012e01430a',
    messagingSenderId: '405198768063',
    projectId: 'fir-auth-7e30b',
    databaseURL: 'https://fir-auth-7e30b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-7e30b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8B_J2AE1RJJqBPK-6A33vR0V1C7TCgEY',
    appId: '1:405198768063:ios:008c87fbd0d2831501430a',
    messagingSenderId: '405198768063',
    projectId: 'fir-auth-7e30b',
    databaseURL: 'https://fir-auth-7e30b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-7e30b.appspot.com',
    iosClientId: '405198768063-98jjjk70t7me20l4v2eln5ae83upl7oc.apps.googleusercontent.com',
    iosBundleId: 'com.snapsid.flutterApp',
  );
}
